name: fake_store_demo
description: "A compact Fake Store demo app for LYQX"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  get_it: ^9.1.0
  go_router: ^16.3.0
  google_fonts: ^6.3.2
  injectable: ^2.5.1
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  injectable_generator: ^2.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/plant_background.png
    - assets/icons/cart_icon.svg
    - assets/icons/fake_store_logo.svg
    - assets/icons/home_icon.svg
